/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_overrun_jni_Download */

#ifndef _Included_io_github_overrun_jni_Download
#define _Included_io_github_overrun_jni_Download
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_overrun_jni_Download
 * Method:    download
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_overrun_jni_Download_download
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
